//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEmployee
    {
        public int Id_PK { get; set; }
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public System.DateTime BirthDate { get; set; }
    }
}
